### ISSUE TITLE
Account flow: create -> delete -> (cannot) import 

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/smapp-lite#100]
Steps: 
1. create a key with an account
2. export account to the file
3. remove key  and the account from wallet
4. try to import the exported file
The last step throws an error as show in the recording

note: I tried closing the browser session/cleaning the cache and all the browsing data/wipe out in the wallet - nothing helps. 

https://github.com/user-attachments/assets/33d58da7-109a-4912-8324-3daac6818334

**Comment by brusherru** [comment]
Hm... I cannot reproduce it.
Are you sure you have deleted the account?

On the video I see that you have this account in the wallet (named "test").

**Comment by monikasmolarek** [comment]
I retried and I have deduced that, clearly, I am an idiot. 
I'm sorry for wasting your time on this one 🫣🤦‍♀️

**Comment by brusherru** [comment]
@monikasmolarek no problem, it happens to everyone :)
