### ISSUE TITLE
Hide Switch button when only one account exist

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/smapp-lite#8]
Once we create a new wallet, we have Account 0 and Account 1 automatically created 
(was it only to test the "Switch" button? Don't forget to fix it back before release)

![Screenshot 2024-05-22 at 21 43 08](https://github.com/spacemeshos/smapp-lite/assets/89876259/1b11a9a4-079e-42f6-94bc-5a98d2fe2fc6)

**Comment by brusherru** [comment]
This button were "merged" with the account name in the new design.
It is still possible to click on it and see that there is the only one account, but I think it is fine to allow get used to the UI even if User does not have more accounts.
I'm closing this issue for now. But if you think we need to improve something — let's open another one and write a proposal.
