### ISSUE TITLE
Add "Create new key" option to key selection drop down in Create/Edit Account popup

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/smapp-lite#82]
As in the rec. Creating a new account will create a new record on the list, but it will be the same exact account. It's not only a displaying issue, the exported account files are also exactly the same. (as discussed - the reason behind it is that the account creation does not automatically create a new key for the account, it uses the existing key)

https://github.com/user-attachments/assets/47f5e5f1-820d-4707-b255-d601e686aae3

<img width="1680" alt="Screenshot 2024-09-10 at 12 53 59" src="https://github.com/user-attachments/assets/6abda30c-7a36-496f-be79-020a76d2797a">

I noticed the same while testing the deleting keys/accounts. 
Delete Key- create a new key pair, you will get the exact same key over and over again. 
I thought that it could be the cache issue? To be checked, I could easily reproduce it

https://github.com/user-attachments/assets/17ef70f5-df44-4d3e-9876-9c1573a1fc01

**Comment by brusherru** [comment]
As we discussed on the call, I'll add "Create a new key" option to the dropdown and make it default (for SingleSig for sure).
Also I think that showing a message is still actual. So I'll add it as well.
Then I think it will be enough UX tweaks to not have confusion anymore. :)
